name: "Destroy Infrastructure"
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Securely pulled from the Secrets Vault
      TF_VAR_exoscale_api_key: ${{ secrets.EXOSCALE_API_KEY }}
      TF_VAR_exoscale_api_secret: ${{ secrets.EXOSCALE_API_SECRET }}

      # Pulled from plain-text Repository Variables
      TF_VAR_root_domain: ${{ vars.ROOT_DOMAIN }}
      TF_VAR_stats_domain: ${{ vars.STATS_PREFIX }}
      TF_VAR_api_domain: ${{ vars.API_PREFIX }}
      TF_VAR_admin_email: ${{ vars.ADMIN_EMAIL }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1

      # Navigate directly into the assignment folder to execute the code
      - name: Initialize & Apply
        working-directory: ./Gruenwald_Georg/Abgabe_2
        run: |
          tofu init
          tofu destroy -auto-approve
